name: Test Project

on:
    schedule:
        - cron: "0 6,7 * * *"

permissions:
    contents: write

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: First test
              run: echo "hello world"

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run file output
              run: actions-test-out.sh

            - name: Commit and push changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

                  if git status --porcelain; then
                    git add .
                    git commit -m "Automated update"
                    git push
                  else
                    echo "No changes to commit"
                  fi
